name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - branch: swift-5.5-branch
            tag: 5.5-DEVELOPMENT-SNAPSHOT-2021-06-02-a

    steps:
    - uses: compnerd/gha-setup-swift@main
      with:
        tag: ${{ matrix.tag }}
        branch: ${{ matrix.branch }}

    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
