name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - branch: swift-5.5-branch
            tag: 5.5-DEVELOPMENT-SNAPSHOT-2021-06-02-a

    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.tag }}
      run: |
        function Update-EnvironmentVariables {
          foreach ($level in "Machine", "User") {
            [Environment]::GetEnvironmentVariables($level).GetEnumerator() | % {
              # For Path variables, append the new values, if they're not already in there
              if ($_.Name -Match 'Path$') {
                $_.Value = ($((Get-Content "Env:$($_.Name)") + ";$($_.Value)") -Split ';' | Select -Unique) -Join ';'
              }
              $_
            } | Set-Content -Path { "Env:$($_.Name)" }
          }
        }

        Install-Binary -Url "https://swift.org/builds/${{ matrix.branch }}/windows10/swift-${{ matrix.tag }}/swift-${{ matrix.tag }}-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
        [Environment]::GetEnvironmentVariables("Machine")
        Update-EnvironmentVariables

    - name: Build
      run: swift build -v
    # - name: Run tests
    #  run: swift test -v
